apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stock-picker.fullname" . }}-env-vars
  labels:
    {{- include "stock-picker.labels" . | nindent 4 }}
data:
  SYMBOL: {{ .Values.config.symbol | quote }}
  NDAYS: {{ .Values.config.nDays | quote }}
  ALPHA_VANTAGE_URL: {{ .Values.config.apiVantageURL | quote }}